version: '3.2'

volumes:
  minio_data: {}

services:
  app:
    build:
      context: .
      dockerfile: ./compose/local/uvicorn/Dockerfile
    image: enrolments_api
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    env_file:
      - ./.envs/.local/.minio
      - ./.envs/.local/.sls
    depends_on:
      - minio
    command: /start

  minio:
    image: minio/minio:latest
    ports:
      - "9001:9000"
    env_file:
      - ./.envs/.local/.minio
    volumes:
      - minio_data:/data
    command: server /data
