version: '3.2'

volumes:
  minio_data: {}

services:
  uvicorn: &uvicorn
    build:
      context: .
      dockerfile: ./compose/local/uvicorn/Dockerfile
    image: local_enrolments_api_app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - ./.envs/.local/.minio
    depends_on:
      - minio
    command: /start

  test:
    <<: *uvicorn
    image: local_enrolments_api_test
    command: python -m pytest

  minio:
    image: minio/minio:latest
    ports:
      - "9001:9000"
    env_file:
      - ./.envs/.local/.minio
    volumes:
      - minio_data:/data
    command: server /data
