version: '3.2'

volumes:
  minio_data: {}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: callback_api
    environment:
      S3_ACCESS_KEY_ID: ACCESS-KEY
      S3_SECRET_ACCESS_KEY: MY-SECRET
      S3_ENDPOINT_URL: http://minio:9000
      CALLBACK_BUCKET: put-callbacks-here
      ENROLMENT_BUCKET: put-enrolments-here
    volumes:
      - .:/app
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    depends_on:
      - minio

  minio:
    image: minio/minio:latest
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: ACCESS-KEY
      MINIO_SECRET_KEY: MY-SECRET
    volumes:
      - minio_data:/data
    command: server /data
